### ISSUE TITLE
SortedMap.iterator() raises TypeError as iterate() is missing

### ISSUE THREAD

**Issue by akloeber** [montagejs/collections#149]
The `iterator()` function seems to be broken in v3.0.0:

```
var SortedMap = require('collections/sorted-map');
var m = new SortedMap();
m.set(3, 'foo');
var it = m.iterator();
```

Result:
```
TypeError: Cannot read property 'apply' of undefined
    at SortedMap.GenericCollection.iterator (/Users/aske/Repos/node-timeseries/node_modules/collections/generic-collection.js:269:24)
```

It looks like `iterate()` is missing completely:
```
var it = m.iterate();
           ^

TypeError: m.iterate is not a function
    at Object.<anonymous> (/Users/aske/Repos/node-timeseries/lib/SortedMap.Collections.SortedMap.js:9:12)
```

**Comment by marchant** [comment]
fix committed to master
