### ISSUE TITLE
MultiMap creation throws UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by adyshimony** [montagejs/collections#192]
var MultiMap = require("collections/multi-map");
let accountsMultiMap = new MultiMap() 

inside async method throws:

  
**(node:26281) UnhandledPromiseRejectionWarning: TypeError: Constructor Map requires 'new'**
warning.js:18
    at MultiMap.Map (<anonymous>)
    at new MultiMap (/home/adys/Sources/supernode-indexer/node_modules/collections/multi-map.js:11:9)
    at router.get (/home/adys/Sources/supernode-indexer/src/routes/api/accountTx.js:22:26)
    at Layer.handle [as handle_request] (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/layer.js:95:5)
    at /home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:281:22
    at param (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:354:14)
    at param (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:365:14)
    at param (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:410:3)
    at next (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:174:3)
    at router (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:317:13)
    at /home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:335:12)
    at next (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:275:10)
    at /home/adys/Sources/supernode-indexer/node_modules/express-winston/index.js:323:9
    at Layer.handle [as handle_request] (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:317:13)
    at /home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:335:12)
    at next (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/home/adys/Sources/supernode-indexer/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:317:13)
    at /home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:335:12)
    at next (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/index.js:275:10)
    at query (/home/adys/Sources/supernode-indexer/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/home/adys/Sources/supernode-indexer/node_modules/express/lib/router/layer.js:95:5)
(node:26281) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
warning.js:18
(node:26281) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by xduseko** [comment]
MultiMap is broken since January?

**Comment by hthetiot** [comment]
fix here https://github.com/montagejs/collections/commit/ecfa4b50be4d11b76622b5924f9b56684460688f

**Comment by hthetiot** [comment]
Fixed in v5.1.4
